---
title: "Geography 13"
author: "[Haylee Damron](https://github.com/hayleed25)"
subtitle: 'Lab 03: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---
# Libraries
```{r}
# SPDS
library(tidyverse)
library(sf)
library(units)

# Data
library(USAboundaries)
library(rnaturalearthdata)

# Visualization
library(gghighlight)
library(ggrepel)
library(knitr)
library(readr)
```

# Question 1
``` {r}
# 1.1- Define A Projection 
eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'

# 1.2- Get State Boundaries 
states = USAboundaries::us_states(resolution = "low") %>% 
  filter(!stusps %in% c("PR", "HI", "AK")) %>% 
  st_transform(eqdc)

# 1.3 - Get country boundaries for Mexico, the United States of America, and Canada
worldboundaries = rnaturalearthdata::countries110 %>% 
  st_as_sf(worldboundaries) %>% 
  filter(admin %in% c("United States of America", "Canada", "Mexico")) %>% 
  st_transform(eqdc)

# 1.4 - Get city locations from the CSV file
uscities = readr::read_csv("../data/uscities.csv") %>% 
  st_as_sf(coords = c("lng", "lat"), crs = 4269) %>% 
  filter(!state_name %in% c("Hawaii", "Puerto Rico", "Alaska")) %>% 
  st_transform(eqdc)
``` 

# Question 2
``` {r}
# 2.1 - Distance to USA Border (coastline or national) (km)
USAboundaries::us_states() %>% 
  filter(!state_name %in% c("Puerto Rico", "Hawaii", "Alaska")) 

border = USAboundaries::us_states() %>%
  filter(!state_name %in% c("Puerto Rico", "Hawaii", "Alaska")) %>% 
  st_union %>% 
  st_cast("MULTILINESTRING")%>% 
  st_transform(eqdc)
plot(border)

distance1.1 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, border)) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(-distance_to_border) %>%
  slice(1:5)
knitr::kable(distance1.1, caption = "5 Cities Furthest From USA Border")

# 2.2 - Distance to States (km)
stateborders = USAboundaries::us_states() %>% 
  filter(!state_name %in% c("Puerto Rico", "Hawaii", "Alaska")) %>% 
  st_combine %>% 
  st_cast("MULTILINESTRING")%>% 
  st_transform(eqdc)
plot(stateborders)

distance2.1 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, border),
        distance_to_border = set_units(distance_to_border, "km")) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(-distance_to_border) %>%
  slice(1:5)
knitr::kable(distance2.1, caption = "5 Cities Furthest From USA Border")

# 2.3 - Distance to Mexico (km)
mexico = rnaturalearthdata::countries110 %>% 
  st_as_sf(worldboundaries) %>% 
  filter(admin %in% c("Mexico"))%>% 
  st_transform(eqdc)

distance3.1 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, mexico),
        distance_to_border = set_units(distance_to_border, "km")) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(-distance_to_border) %>%
  slice(1:5) 
knitr::kable(distance3.1, caption = "5 Cities Furthest From Mexican Border")

# 2.4 - Distance to Canada (km)
canada = rnaturalearthdata::countries110 %>% 
  st_as_sf(worldboundaries) %>% 
  filter(admin %in% c("Canada"))%>% 
  st_transform(eqdc)

distance4.1 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, canada),
        distance_to_border = set_units(distance_to_border, "km")) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(-distance_to_border) %>%
  slice(1:5) 
knitr::kable(distance4.1, caption = "5 Cities Furthest From Canadian Border")
``` 

# Question 3
``` {r}
# 3.1 Data
top10 = uscities %>% 
  select(city, population) %>% 
  slice_max(population, n = 10)
continents = rnaturalearthdata::countries110 %>% 
  st_as_sf(continents) %>% 
  filter(admin %in% c("United States of America", "Canada", "Mexico")) %>% 
  select(name, geometry) %>% 
  st_transform(eqdc)
plot(continents['name'], key.pos = 1)
combined_c = st_combine(continents)
ggplot() +
  geom_sf(data = combined_c, lty = 3) +
  geom_sf(data = stateborders, lty = 3) +
  geom_sf(data = top10, lty = .5, col = "red") +
  ggrepel::geom_label_repel(
    data = top10,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3)

# 3.2 City Distance from the Border
allcities = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, border),
         distance_to_border = set_units(distance_to_border, "km")) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(-distance_to_border)

ggplot()+
  geom_sf(data = stateborders) +
  geom_sf(data = allcities, aes(col = as.numeric(distance_to_border)))+
  scale_colour_gradient(low = "#132B43",
  high = "#56B1F7",
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour") +
  geom_sf(data = distance2.1, col = "red", lty = 3) +
  ggrepel::geom_label_repel(
    data = distance2.1,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(col = "Distance To Border", 
       title = "Cities Distance From Border",
       x = "", 
       y = "") +
  ggthemes::theme_map()

#3.3 City Distance from Nearest State
statecities = uscities %>% 
  mutate(distance_state_border = st_distance(uscities, stateborders),
         distance_state_border = set_units(distance_state_border, "km")) %>% 
  select(city, distance_state_border, state_name) %>%
  arrange(-distance_state_border)
  

ggplot()+
  geom_sf(data = stateborders) +
  geom_sf(data = statecities, aes(col = as.numeric(distance_state_border)))+
  scale_colour_gradient(low = "99009", high = "663366") +
  geom_sf(data = distance2.1, col = "red", lty = 3) +
  ggrepel::geom_label_repel(
    data = distance2.1,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(col = "Distance To State Border", 
       title = "Cities Distance To State Border",
       x = "", 
       y = "") +
  ggthemes::theme_map()

#3.4 Equidistance boundary from Mexico and Canada
equi = uscities %>% 
  mutate(equidistance = st_distance(canada, mexico),
         equidistance = set_units(equidistance, "km")) %>% 
  select(city, equidistance, state_name) %>% 
  arrange(-equidistance)

ggplot()+
  geom_sf(data = continents) +
  geom_sf(data = equi, aes(col = as.numeric(equidistance)))+
  scale_colour_gradient(low = "99009", high = "663366") +
  geom_sf(data = distance2.1, col = "red", lty = 3) +
  ggrepel::geom_label_repel(
    data = distance2.1,
    aes(label = city, geometry = geometry),
    stat = "sf_coordinates",
    size = 3) +
  labs(col = "Distance To State Border", 
       title = "Equidistance",
       x = "", 
       y = "") +
  ggthemes::theme_map()
  
``` 

# Question 4
```{r}
#4.1 Quantifing Border Zone
# How many cities are in this 100 mile zone? (100 miles ~ 160 kilometers)
top100 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, border),
         distance_to_border = set_units(distance_to_border, "km")) %>%
  select(city, distance_to_border, state_name) %>%
  arrange(distance_to_border) %>% 
  slice(1:12008)
count(top100)
# 12008

# How many people live in a city within 100 miles of the border?
pop100 = uscities %>% 
  mutate(distance_to_border = st_distance(uscities, border),
         distance_to_border = set_units(distance_to_border, "km")) %>% 
  select(population, state_name, city)
count(pop100)
# 27620

centroid = st_centroid(states)

ggplot()+
  geom_sf(data = stateborders)+
  geom_sf(data = top100, aes(col = as.numeric(distance_to_border)))+
  # Extra Credit 
  geom_sf(data = centroid, col = "red", lty = 3)+
  scale_color_gradient(low = "red",
  high = "orange") +
  labs(col = "Top 100 Cities in Danger Zone", 
       title = "Top 100 Cities",
       x = "", 
       y = "") +
  ggthemes::theme_map()
```

